# -*- coding: utf-8 -*-
"""SVM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TyoqM6DFLvoDzcGArnu82TFk378qDsGd
"""

# Date 27 March 2024.
# Notes & solution by Akhona Njeje.
# Topic : Quantum AI, support vector machines.

!pip install dlx docplex fastdtw h5py

!pip install --upgrade setuptools wheel

!pip install cvxpy

!pip install qiskit

import qiskit

from matplotlib import pyplot as plt
import numpy as np

!pip install --upgrade qiskit

!pip install qiskit-machine-learning

from qiskit_machine_learning.datasets import ad_hoc_data

from qiskit.providers.basicaer import BasicAer

from qiskit import BasicAer









